version: '3.8'
services:
  app:
    build: .
    platform: linux/x86_64
    container_name: documents-api
    restart: always
    env_file: .env
    #ports:
    #  - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    #environment:
    #  SPRING_APPLICATION_JSON: '{
    #        "spring.datasource.username": "$MYSQLDB_USER",
    #        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
    #        "spring.datasource.url"  : "jdbc:mysql://$MYSQLDB_DOCKER_HOST/$MYSQLDB_DATABASE",
    #        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
    #        "spring.graphql.graphiql.enabled": "true"
    #      }'
    volumes:
      - .m2:/root/.m2